name: Get recent rss post

on:
  # push:
  #   branches:
  #     - main
  #     - master
  # release:
  #   types: [published]
  watch:
    types: [started]
  schedule:
    # * is a special character in YAML so you have to quote this string
    # UTC 17:00 -> CST (China) 1:00, see https://datetime360.com/cn/utc-cst-china-time/
    - cron: '0 17 * * *'
    # 每月最后一天10:15分运行
    # - cron: '0 15 10 L * ?'
    # 每月第一天0:0分运行
    # - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  build_recent_post:
    name: Build Recent Posts
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        architecture: 'x64'
       
    - name: Generate README.md for github.com
      env:
       GH_REPO: github.com/appotry/appotry.git
      run: |
       mkdir -p /home/runner/work/artifacts/
       cd /home/runner/work/artifacts/
       git clone https://github.com/appotry/appotry.git 
       cd /home/runner/work/artifacts/appotry
       git config user.name "appotry"
       git config user.email "andycrusoe@gmail.com"
       rm -f README.md

       # 安装依赖到虚拟环境
       python -m venv venv
       source venv/bin/activate
       venv/bin/pip install pip -U
       #  venv/bin/pip config set global.index-url http://mirrors.aliyun.com/pypi/simple/
       #  venv/bin/pip config set install.trusted-host mirrors.aliyun.com
       venv/bin/pip install -r requirements.txt 

       python generator.py
       
       git add -f README.md
       git commit -m "Update README.md by Github Action"
       git push --force --quiet "https://${{ secrets.CI_TOKEN }}@$GH_REPO" main:main
